version: "3.8"

services:
  frontend:
    image: alwiassidiqi/fullstack-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    image: alwiassidiqi/fullstack-backend:latest
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=mydb
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
